# Generated by Django 5.2 on 2025-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Cliente'), ('seller', 'Vendedor'), ('admin', 'Administrador')], default='customer', max_length=20),
        ),
    ]
