# Generated by Django 5.2 on 2025-11-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_inventorymovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-created_at']},
        ),
    ]
